#ifndef BLINK_WIN_COSMO_SYSCALL_SUPPORT_NT_INTERNAL_H_
#define BLINK_WIN_COSMO_SYSCALL_SUPPORT_NT_INTERNAL_H_

int64_t __fix_enotdir(int64_t, wchar_t *);

#endif /* BLINK_WIN_COSMO_SYSCALL_SUPPORT_NT_INTERNAL_H_ */
